name: Dispatched
on:
  pull_request:
    types: [synchronize]
permissions:
  checks: read

jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sleep for 60 seconds
        run: sleep 15s
        shell: bash
