name: Dispatched
on:
  check_run:
    types: [completed]
permissions:
  check: read

jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
