name: CI

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: customAction
        uses: ./.github/actions/custom-action

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{steps.customAction.outputs.data}}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
