name: CI

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: customAction
        name: 'Check Approves'
        uses: './.github/actions/custom-action'
        with:
          approve_count: 1

      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: ${{ steps.customAction.outputs.data == true }}
        run: echo 'plus'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: ${{ steps.customAction.outputs.data == true }}
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
