name: CI

on: [pull_request_review]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: 'reviews'
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: 'steps.reviews.outputs.approved == 1 && steps.reviews.outputs.changes_requested == 0'
        run: echo 'plus'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
