name: CI
on:
  pull_request:
    types: [synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  checkApproves:
    if: github.event_name == 'pull_request' || github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: checkApproves
        name: 'Check Approves'
        uses: './.github/actions/custom-action'
        with:
          approve_count: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/repository-dispatch@v2
        name: 'Dispatch Sub Workflow'
        with:
          event-type: my-event
    # outputs:
    #   approved: ${{ steps.checkApproves.outputs.data }}
