name: Sub
on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  build:
    needs: checkApproves
    if: ${{needs.checkApproves.outputs.approved == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo 'plus'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
